Repository wecode-bootcamp-korea/14-1st-O9O9-backend, pull requests merged in 2020-11, with the labels that each got.

#1 models.py 작성 / gitignore 수정(pycharm 내용추가) settings.py 타임존설정추가
  .gitignore
  o9o9/settings.py
  order/__init__.py
  order/admin.py
  order/apps.py
  order/migrations/0001_initial.py
  order/migrations/__init__.py
  order/models.py
  order/tests.py
  order/views.py
  product/__init__.py
  product/admin.py
  product/apps.py
  product/migrations/0001_initial.py
  product/migrations/__init__.py
  product/models.py
  product/tests.py
  product/views.py
  review/__init__.py
  review/admin.py
  review/apps.py
  review/migrations/__init__.py
  review/models.py
  review/tests.py
  review/views.py
  user/__init__.py
  user/admin.py
  user/apps.py
  user/migrations/0001_initial.py
  user/migrations/__init__.py
  user/models.py
  user/tests.py
  user/views.py
Labels: Status: 수정 요청

#4 [이민영] 장바구니 품목 추가/조회/수정/삭제 기능구현
  .gitignore
  AnswerStatus.csv
  QuestionType.csv
  o9o9/urls.py
  order/migrations/0003_auto_20201122_2040.py
  order/migrations/0004_delete_cartitem.py
  order/models.py
  order/urls.py
  order/views.py
  product/migrations/0003_auto_20201122_2040.py
  product/migrations/0004_auto_20201124_1415.py
  product/models.py
  review/migrations/0002_auto_20201124_1415.py
  review/models.py
  user/utils.py
Labels: Status: 리뷰 요청

#3 [박승제]checkid테이블 삭제, 자원중복 status code 409로 변경, 필요없는 주석 삭제, url경로 변경, csv파일 추가 / review앱내에 문의하기 화면표시부분 response기능, 문의하기 crud구현, REST API 사용
  .gitignore
  o9o9/settings.py
  o9o9/urls.py
  order/migrations/0003_auto_20201123_2036.py
  order/migrations/0004_cartitem.py
  order/models.py
  product/migrations/0003_auto_20201121_2134.py
  product/migrations/0004_auto_20201121_2137.py
  product/migrations/0005_auto_20201123_2012.py
  product/migrations/0006_auto_20201123_2055.py
  product/models.py
  product/views.py
  requirements.txt
  review/migrations/0002_auto_20201120_1555.py
  review/migrations/0003_auto_20201121_0135.py
  review/migrations/0004_answer_status.py
  review/migrations/0005_auto_20201121_1809.py
  review/migrations/0006_auto_20201123_2012.py
  review/models.py
  review/urls.py
  review/views.py
  user/migrations/0002_checkid.py
  user/migrations/0003_auto_20201119_1923.py
  user/migrations/0004_delete_checkid.py
  user/migrations/0005_allow.py
  user/migrations/0006_auto_20201125_1324.py
  user/models.py
  user/templates/email/send_email.html
  user/templates/email/verify_email.html
  user/urls.py
  user/utils.py
  user/views.py
Labels: Status: 리뷰 요청

#5 Feature/productlist
  .gitignore
  .idea/14-1st-O9O9-backend.iml
  .idea/inspectionProfiles/profiles_settings .xml
  .idea/misc.xml
  .idea/modules.xml
  o9o9/urls.py
  order/migrations/0001_initial.py
  order/migrations/0002_auto_20201118_2156.py
  order/migrations/0002_auto_20201126_0320.py
  order/models.py
  product/migrations/0001_initial.py
  product/migrations/0002_auto_20201118_2156.py
  product/models.py
  product/urls.py
  product/views.py
  review/migrations/0001_initial.py
  user/migrations/0001_initial.py
Labels: Status: 컨플릭트 해결 요청

#7 feature/productlist
  AnswerStatus.csv
  QuestionType.csv
  product/views.py
Labels: Status: 리뷰 요청
